# Generated by Django 4.2.26 on 2025-11-15 04:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('voter_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint_template', models.BinaryField(max_length=534)),
                ('firebase_template_id', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar number must be 12 digits')])),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be 10 digits')])),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('is_eligible', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_vote_date', models.DateTimeField(blank=True, null=True)),
                ('blockchain_address', models.CharField(blank=True, max_length=42, null=True)),
                ('registration_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
                'db_table': 'voting_voter',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlockchainSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('block_number', models.IntegerField()),
                ('transaction_count', models.IntegerField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCING', 'Syncing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'voting_blockchain_sync',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('previous_experience', models.TextField(blank=True)),
                ('blockchain_candidate_id', models.IntegerField(blank=True, null=True)),
                ('registration_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voting_candidate',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('election_type', models.CharField(choices=[('GENERAL', 'General Election'), ('LOCAL', 'Local Election'), ('SPECIAL', 'Special Election')], max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('smart_contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('deployment_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'voting_election',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('esp32_device_id', models.CharField(max_length=100)),
                ('fingerprint_match_score', models.FloatField()),
                ('voting_timestamp', models.DateTimeField(auto_now_add=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('blockchain_block_number', models.IntegerField(blank=True, null=True)),
                ('vote_status', models.CharField(choices=[('PENDING', 'Pending Blockchain Confirmation'), ('CONFIRMED', 'Blockchain Confirmed'), ('FAILED', 'Transaction Failed')], default='PENDING', max_length=20)),
                ('gas_used', models.IntegerField(blank=True, null=True)),
                ('vote_hash', models.CharField(max_length=64)),
                ('fingerprint_template_hash', models.CharField(max_length=64)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voting_vote',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.election'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('log_type', models.CharField(choices=[('VOTER_REGISTRATION', 'Voter Registration'), ('VOTE_CAST', 'Vote Cast'), ('BLOCKCHAIN_TX', 'Blockchain Transaction'), ('AUTHENTICATION', 'Authentication'), ('SYSTEM_ACCESS', 'System Access'), ('ERROR', 'System Error')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('action', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('esp32_device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.election')),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.vote')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voting_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['election', 'candidate'], name='voting_vote_electio_05e886_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['blockchain_tx_hash'], name='voting_vote_blockch_3ba5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voting_timestamp'], name='voting_vote_voting__b6389e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'position')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['log_type', 'timestamp'], name='voting_audi_log_typ_701ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['voter', 'timestamp'], name='voting_audi_voter_i_e2ab29_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['blockchain_tx_hash'], name='voting_audi_blockch_34f485_idx'),
        ),
    ]
