# Generated by Django 4.2.26 on 2025-11-15 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar number must be 12 digits')]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='fingerprint_template',
            field=models.BinaryField(blank=True, max_length=534, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be 10 digits')]),
        ),
    ]
